In [1]:
%load_ext autoreload
%autoreload 2

import warnings
warnings.filterwarnings("ignore")

import sys
sys.path.insert(0, '..')

import os
import definition
import numpy as np
from utility import Clusterer, Embedding

## Embedding Model Loading

In [2]:
embedding_filename = "fasttext_25.bin"

embedding = Embedding()
embedding.load(os.path.join(definition.MODEL_UTILITY, embedding_filename))

In [3]:
data = [embedding.get_vector_word(word) for word in embedding.model.wv.vocab]
len(data)

6734

In [4]:
data[0]

array([-0.49544296, -1.2553488 ,  1.0667154 ,  2.5983744 , -2.9989235 ,
       -1.9667577 ,  1.59595   ,  1.7653427 ,  0.99862975, -2.3931577 ,
        1.5110081 , -1.1557192 , -0.69728655,  3.2471025 ,  2.943425  ,
       -1.9196078 , -5.405115  , -1.0559725 , -2.396467  ,  2.3159554 ,
        1.1990556 , -0.04925343, -2.8697078 ,  0.11827862, -3.3559096 ],
      dtype=float32)

## Clustering

In [5]:
# important parameter
n_clusters = 10

In [6]:
clusterer = Clusterer(n_clusters=10)
clusterer.fit(X=data)

In [7]:
clusterer_filename = "kmeans_{}.bin".format(n_clusters)
clusterer.save(os.path.join(definition.MODEL_UTILITY, clusterer_filename))

In [8]:
clst = Clusterer(n_clusters=1)
clst.load(os.path.join(definition.MODEL_UTILITY, clusterer_filename))

In [9]:
clst.predict([[-0.49544296, -1.2553488 ,  1.0667154 ,  2.5983744 ,  2.9989235 ,
       -1.9667577 ,  1.59595   ,  1.7653427 ,  0.99862975,  2.3931577 ,
        1.5110081 ,  1.1557192 ,  0.69728655,  3.2471025 ,  2.943425  ,
       -1.9196078 , -5.405115  , -1.0559725 , -2.396467  ,  2.3159554 ,
        1.1990556 , -0.04925343, -2.8697078 ,  0.11827862,  3.3559096 ]])

array([0])

In [10]:
clst.model.cluster_centers_

array([[-2.77517302e-02, -4.47991178e-01, -2.68827604e-01,
         5.55738514e-01,  3.07234716e-01,  9.17787601e-01,
        -1.56435020e-01, -7.73880579e-01, -1.44212273e-01,
        -3.15764648e-01,  2.27471456e-01,  1.58042157e-01,
        -2.02619020e-01,  2.68115066e-02, -4.21827054e-01,
        -5.33942301e-01, -3.00529369e-01,  1.26787940e-01,
         1.32156316e-01, -1.27898480e-01, -4.52408389e-01,
         1.30330342e-02, -1.07168257e-01, -3.75273843e-01,
        -3.45010114e-01],
       [ 1.34850419e+00, -9.37918631e-03,  9.56911757e-01,
         1.44813957e+00, -9.25666421e-02, -2.39300668e-01,
         1.46424149e-03, -4.92800097e-01,  1.10594626e-01,
        -5.76546546e-01,  5.97153099e-02,  6.22833522e-01,
         1.21744972e+00,  1.10005392e+00, -1.97685600e+00,
        -1.88616315e+00, -1.05671735e+00,  8.01192049e-01,
        -1.28136925e+00,  1.32335838e-01, -4.81686892e-01,
        -1.32447392e-01, -1.02310633e-01, -2.25032756e+00,
        -1.36835873e+00],
    