In [1]:
%load_ext autoreload
%autoreload 2

import warnings
warnings.filterwarnings("ignore")

import sys
sys.path.insert(0, '..')

import os
import definition
import numpy as np
from utility import Clusterer, Embedding

## Embedding Model Loading

In [2]:
embedding_filename = "word2vec_25.bin"

embedding = Embedding()
embedding.load(os.path.join(definition.MODEL_UTILITY, embedding_filename))

In [3]:
data = [embedding.get_vector_word(word) for word in embedding.model.wv.vocab]
len(data)

6711

In [4]:
data[0]

array([-3.7880533 ,  2.420463  , -0.78676724,  4.041538  , -1.888083  ,
       -1.3105453 ,  0.38962078,  2.8784547 , -0.10843739, -5.3605647 ,
       -8.807101  , -3.17065   ,  1.2966547 , -1.4100099 ,  1.348949  ,
        0.8226904 , -0.26717627,  2.1389434 , -0.28743103,  0.71293837,
       -0.8048726 ,  1.3753015 ,  0.5846895 ,  1.9612929 ,  4.0513773 ],
      dtype=float32)

## Clustering

In [5]:
# important parameter
n_clusters = 10

In [6]:
clusterer = Clusterer(n_clusters=10)
clusterer.fit(X=data)

In [7]:
clusterer_filename = "{}_kmeans_{}.pkl".format(embedding_filename[:-4], n_clusters)
clusterer.save(os.path.join(definition.MODEL_UTILITY, clusterer_filename))

In [8]:
clst = Clusterer(n_clusters=1)
clst.load(os.path.join(definition.MODEL_UTILITY, clusterer_filename))

In [9]:
clst.predict([[-0.49544296, -1.2553488 ,  1.0667154 ,  2.5983744 ,  2.9989235 ,
       -1.9667577 ,  1.59595   ,  1.7653427 ,  0.99862975,  2.3931577 ,
        1.5110081 ,  1.1557192 ,  0.69728655,  3.2471025 ,  2.943425  ,
       -1.9196078 , -5.405115  , -1.0559725 , -2.396467  ,  2.3159554 ,
        1.1990556 , -0.04925343, -2.8697078 ,  0.11827862,  3.3559096 ]])

array([1])

In [10]:
clst.model.cluster_centers_

array([[ 0.13470813,  0.01277312,  0.23388426, -0.16107259, -0.38641798,
        -0.07943464, -0.1742019 ,  0.03629456,  0.1176665 ,  0.0485352 ,
        -0.01258997, -0.01451928,  0.26177067,  0.19690216,  0.22839074,
         0.10688033, -0.18153385, -0.21120212,  0.1440967 , -0.08748709,
        -0.01748118, -0.02592863, -0.15623486, -0.02554711, -0.12715415],
       [ 1.53366751, -0.31745596,  1.2377906 ,  1.01828681,  0.37037594,
         0.43179705,  0.30331091, -0.68071085, -0.54978012,  0.14629558,
         1.92156975,  0.99925474,  0.43842136,  0.7483199 ,  1.75662266,
         0.13731168,  0.1396833 ,  1.0904226 , -0.47071301, -1.2967391 ,
         0.9136213 ,  0.40326176, -0.26908792,  1.47702636,  0.90889237],
       [-1.99870087, -1.53562475, -0.23847848, -0.66295706, -0.36805942,
        -1.27197919, -0.61949293, -0.43567947,  2.77754688,  1.17653827,
        -0.36273599, -0.37629711,  1.46405532,  0.1119123 ,  1.09506673,
         0.05057318,  0.45340017,  0.77069034, -0